from sqlalchemy import Column, Integer, DateTime, BigInteger, VARCHAR, FLOAT, DECIMAL, Text

from database.connect_mysql import Base


class Property(Base):
    __tablename__ = "property"

    id = Column(BigInteger, primary_key=True)
    property_code = Column(VARCHAR(length=255), primary_key=True)
    company_classification = Column(VARCHAR)
    property_classification = Column(VARCHAR)
    area = Column(VARCHAR)
    name = Column(VARCHAR)
    building_number = Column(VARCHAR)
    location_prefecture = Column(VARCHAR)
    location_district = Column(VARCHAR)
    location_ward = Column(VARCHAR)
    location_ward_block = Column(VARCHAR)
    location_ward_block_group = Column(VARCHAR)
    nearest_station_railaway_1 = Column(VARCHAR)
    nearest_station_1 = Column(VARCHAR)
    walking_to_nearest_station_1 = Column(Integer)
    busg_to_nearest_station_1 = Column(Integer)
    nearest_station_railaway_2 = Column(VARCHAR)
    nearest_station_2 = Column(VARCHAR)
    walking_to_nearest_station_2 = Column(Integer)
    busg_to_nearest_station_2 = Column(Integer)
    condominium_price_min = Column(FLOAT)
    condominium_price_max = Column(FLOAT)
    condominium_area_min = 	Column(DECIMAL)
    condominium_area_max = Column(DECIMAL)
    condominium_room_type_min = Column(VARCHAR)
    condominium_room_type_max = Column(VARCHAR)
    numbers_of_floors = Column(VARCHAR)
    completion_date = Column(DateTime)
    total_of_units = Column(Integer)
    seller_1 = Column(VARCHAR)
    seller_2 = Column(VARCHAR)
    seller_3 = Column(VARCHAR)
    seller_4 = Column(VARCHAR)
    seller_5 = Column(VARCHAR)
    management_fee = Column(VARCHAR)					
    repair_costs = Column(VARCHAR)
    parking_lot = Column(Integer)
    parking_lot_note = Column(Text)
    concierge_service = Column(Integer)
    all_day_management = Column(Integer)
    recomment_flg = Column(Integer)
    referral_stop_flg = Column(Integer)
    image_flg = Column(Integer)
    appearance_image_link = Column(VARCHAR)
    property_note = Column(Text)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)


class PropertyCondominium(Base):
    __tablename__="property_condominium"

    id = Column(BigInteger, primary_key=True)
    property_id = Column(Integer)
    condominium_code = Column(Integer)
    condominium_number = Column(VARCHAR)
    price = Column(Integer)
    area = Column(Integer)
    room_type = Column(VARCHAR(length=100))
    room_numbers = Column(VARCHAR)
    commission = Column(FLOAT)
    movein_immediate = Column(DateTime)
    movein_period = Column(DateTime)
    direction = Column(VARCHAR)
    top_floor = Column(Integer)
    roof_balcony = Column(Integer)
    private_garden_terrace = Column(Integer)
    assumed_rent_money = Column(Integer)
    profits = Column(Integer)
    furnishing = Column(Integer, default=1)
    image_flg = Column(Integer, default=1)
    appearance_image_link = Column(VARCHAR)
    condominium_note = Column(VARCHAR)
    recomment_flg = Column(Integer)
    referral_stop_flg = Column(Integer)
    closed_flg = Column(Integer)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)