from sqlalchemy import Column, Integer, DateTime, BigInteger, VARCHAR, BINARY, Text

from database.connect_mysql import Base

class Customers(Base):
    __tablename__="customers"

    id = Column(BigInteger, primary_key=True, index=True, nullable=False)
    customer_code = Column(VARCHAR(length=255))
    full_name_kanji = Column(VARCHAR(length=255))
    full_name_furigana = Column(VARCHAR(length=255))
    gender = Column(VARCHAR(length=50))
    birthday = Column(DateTime)
    address_prefecture = Column(VARCHAR(length=255))
    address_district = Column(VARCHAR(length=255))
    address_ward = Column(VARCHAR(length=255))
    address_ward_block = Column(VARCHAR(length=255))
    address_ward_block_group = Column(VARCHAR(length=255))
    address_housing_numbers = Column(VARCHAR(length=255))
    tel = Column(VARCHAR(length=255))
    email = Column(VARCHAR(length=255))
    family_size = Column(Integer)
    family_composition = Column(VARCHAR)
    family_composition_other = Column(VARCHAR(length=1000))
    purchase_purpose_1 = Column(VARCHAR(length=100))
    purchase_purpose_2 = Column(VARCHAR(length=100))
    purchase_purpose_3 = Column(VARCHAR)
    purchase_purpose_other= Column(VARCHAR(length=1000))
    working_company_name = Column(VARCHAR(length=500))
    demand_parking_lot = Column(VARCHAR)
    budget_min = Column(Integer)
    budget_max = Column(Integer)
    own_funds_min = Column(Integer)
    own_funds_max = Column(Integer)
    demand_area_min = Column(Integer)
    demand_area_max = Column(Integer)
    demand_room_type_min = Column(VARCHAR(length=100))
    demand_room_type_max = Column(VARCHAR(length=100))
    customer_note = Column(Text)
    recommend_flg = Column(BINARY)
    person_in_charge = Column(Integer)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)


class Inquiry(Base):
    __tablename__= "inquiry"
    id = Column(BigInteger, primary_key=False)
    property_id = Column(BigInteger)
    inquiry_classification = Column(Integer)
    property_name = Column(VARCHAR(length=255))
    name = Column(VARCHAR(length=255))
    name_furigana = Column(VARCHAR(length=255))
    gender = Column(VARCHAR(length=255))
    birthday = Column(DateTime)
    address_prefecture = Column(VARCHAR(length=255))
    address_district = Column(VARCHAR(length=255))
    address_ward = Column(VARCHAR(length=255))
    address_ward_block = Column(VARCHAR(length=255))
    address_ward_block_group = Column(VARCHAR(length=255))
    address_housing_numbers = Column(VARCHAR(length=255))
    tel = Column(VARCHAR(length=255))
    email = Column(VARCHAR(length=255))
    inquiry_note = Column(Text)
    following_flag = Column(Integer)
    following_username = Column(VARCHAR(length=255))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)